export const QUEUE_ENTRY_STATUS = {
  WAITING: "WAITING",
  CALLED: "CALLED",
  SERVED: "SERVED",
  SKIPPED: "SKIPPED",
  CANCELLED: "CANCELLED",
};

export const ACTIVE_QUEUE_STATUSES = [
  QUEUE_ENTRY_STATUS.WAITING,
  QUEUE_ENTRY_STATUS.CALLED,
];

export const TERMINAL_QUEUE_STATUSES = [
  QUEUE_ENTRY_STATUS.SERVED,
  QUEUE_ENTRY_STATUS.SKIPPED,
  QUEUE_ENTRY_STATUS.CANCELLED,
];
