const QUEUE_ENTRY_STATUS = {
  WAITING: "WAITING",
  CALLED: "CALLED",
  SERVED: "SERVED",
  SKIPPED: "SKIPPED",
  CANCELLED: "CANCELLED",
};

const ACTIVE_QUEUE_STATUSES = [
  QUEUE_ENTRY_STATUS.WAITING,
  QUEUE_ENTRY_STATUS.CALLED,
];

const TERMINAL_QUEUE_STATUSES = [
  QUEUE_ENTRY_STATUS.SERVED,
  QUEUE_ENTRY_STATUS.SKIPPED,
  QUEUE_ENTRY_STATUS.CANCELLED,
];
export { QUEUE_ENTRY_STATUS, ACTIVE_QUEUE_STATUSES, TERMINAL_QUEUE_STATUSES };
